# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: fluentbit

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
